#Requires -Version 5.1
<#
    monkeycode-sync.ps1   (TWO-WAY)

    Watches a GitHub repo and a local folder in BOTH directions:

        repo  ->  folder   MonkeyCode edits appear on your PC automatically.
        folder ->  repo    Your PC edits are committed + pushed automatically.

    Works on Windows 10 Pro + PowerShell 5.1. Browser independent
    (works while MonkeyCode runs in Brave, Chrome, Edge, Firefox...).

    Defaults:
      Repo   : https://github.com/zebronicsmaxfury-droid/fortnite
      Branch : main
      Target : C:\Users\hxh\Desktop\games!
      Scan   : every 3 seconds

    You normally do NOT edit this file. Double-click monkeycode-sync.bat.
    If you must change something, edit the param block below.

    Extra switches:
      -Once      run a single sync cycle then exit
      -OneWay    disable folder -> repo (old one-way behaviour)
#>

[CmdletBinding()]
param(
    [string]$RepoUrl  = "https://github.com/zebronicsmaxfury-droid/fortnite.git",
    [string]$Branch   = "main",
    [string]$Target   = "C:\Users\hxh\Desktop\games!",
    [int]   $Interval = 3,
    [string]$RepoDir  = (Join-Path $env:USERPROFILE ".monkeycode-sync\repo"),
    [string]$StateFile = (Join-Path $env:USERPROFILE ".monkeycode-sync\state.json"),
    [string]$ConflictDir = (Join-Path $env:USERPROFILE ".monkeycode-sync\conflicts"),
    [string]$GitName  = "monkeycode-sync",
    [string]$GitEmail = "monkeycode-sync@local",
    [string]$CommitMessage = "Auto-sync from PC",
    [bool]  $AllowDelete = $true,
    [string[]]$Ignore = @('*.tmp','*.temp','~*','*~','*.swp','*.swo','*.bak','*.orig','.DS_Store','Thumbs.db'),
    [switch]$OneWay,
    [switch]$Once
)

$ErrorActionPreference = 'Continue'

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
function Write-Log {
    param(
        [string]$Message,
        [string]$Level = 'INFO'
    )
    $time  = Get-Date -Format 'HH:mm:ss'
    $color = 'Gray'
    switch ($Level) {
        'OK'    { $color = 'Green'   }
        'FILE'  { $color = 'Cyan'    }
        'PC'    { $color = 'Magenta' }
        'WARN'  { $color = 'Yellow'  }
        'ERROR' { $color = 'Red'     }
    }
    Write-Host ("[{0}] [{1}] {2}" -f $time, $Level, $Message) -ForegroundColor $color
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Invoke-Git {
    param([string[]]$GitArgs)
    $out = & git -C $RepoDir @GitArgs 2>&1
    return @{
        Code   = $LASTEXITCODE
        Output = (($out | Out-String) -replace "`r", "").Trim()
    }
}

function Get-ContentHash {
    param([string]$Path)
    try {
        return (Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash
    }
    catch {
        return $null
    }
}

function Test-Ignored {
    param([string]$Name)
    foreach ($pattern in $Ignore) {
        if ($Name -like $pattern) { return $true }
    }
    return $false
}

# Build a hashtable of relative path -> SHA256 for every file under $Root.
# The .git folder is skipped, as are editor/temp files in $Ignore.
function Get-TreeHashes {
    param([string]$Root)

    $map = @{}
    if (-not (Test-Path -LiteralPath $Root)) { return $map }

    $stack = New-Object System.Collections.Stack
    $stack.Push($Root)

    while ($stack.Count -gt 0) {
        $dir = $stack.Pop()
        try {
            $children = Get-ChildItem -LiteralPath $dir -Force -ErrorAction Stop
        }
        catch {
            continue
        }
        foreach ($child in $children) {
            if ($child.PSIsContainer) {
                if ($child.Name -ne '.git') { $stack.Push($child.FullName) }
                continue
            }
            if (Test-Ignored $child.Name) { continue }

            $rel = $child.FullName.Substring($Root.Length).TrimStart('\', '/') -replace '\\', '/'
            $hash = Get-ContentHash $child.FullName
            if ($hash) { $map[$rel] = $hash }
        }
    }
    return $map
}

function ConvertTo-OsPath {
    param([string]$RelativePath)
    return ($RelativePath -replace '/', '\')
}

function Copy-RepoToTarget {
    param([string]$RelativePath, [string]$RepoHash)

    $src = Join-Path $RepoDir (ConvertTo-OsPath $RelativePath)
    $dst = Join-Path $Target  (ConvertTo-OsPath $RelativePath)

    if ($RepoHash) {
        $dstDir = Split-Path -Parent $dst
        if ($dstDir -and -not (Test-Path -LiteralPath $dstDir)) {
            New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
        }
        Copy-Item -LiteralPath $src -Destination $dst -Force
        Write-Log ("REPO->PC  {0}" -f $RelativePath) 'FILE'
    }
    elseif (Test-Path -LiteralPath $dst) {
        Remove-Item -LiteralPath $dst -Force
        Write-Log ("REPO->PC  deleted {0}" -f $RelativePath) 'FILE'
    }
}

function Backup-TargetFile {
    param([string]$RelativePath)

    $src = Join-Path $Target (ConvertTo-OsPath $RelativePath)
    if (-not (Test-Path -LiteralPath $src)) { return }

    $stamp   = Get-Date -Format 'yyyyMMdd-HHmmss'
    $destDir = Join-Path $ConflictDir $stamp
    $dest    = Join-Path $destDir (ConvertTo-OsPath $RelativePath)

    $destParent = Split-Path -Parent $dest
    if ($destParent -and -not (Test-Path -LiteralPath $destParent)) {
        New-Item -ItemType Directory -Force -Path $destParent | Out-Null
    }
    Copy-Item -LiteralPath $src -Destination $dest -Force
    return $dest
}

function Load-State {
    $map = @{}
    if (Test-Path -LiteralPath $StateFile) {
        try {
            $raw = Get-Content -LiteralPath $StateFile -Raw -ErrorAction Stop
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                $obj = $raw | ConvertFrom-Json
                foreach ($prop in $obj.PSObject.Properties) {
                    $map[$prop.Name] = [string]$prop.Value
                }
            }
        }
        catch {
            Write-Log "Could not read state file; starting fresh." 'WARN'
        }
    }
    return $map
}

function Save-State {
    param($Map)

    $parent = Split-Path -Parent $StateFile
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    if ($Map.Count -eq 0) {
        Set-Content -LiteralPath $StateFile -Value '{}' -Encoding UTF8
        return
    }

    $ordered = [ordered]@{}
    foreach ($key in ($Map.Keys | Sort-Object)) {
        $ordered[$key] = $Map[$key]
    }
    ($ordered | ConvertTo-Json -Depth 3) | Set-Content -LiteralPath $StateFile -Encoding UTF8
}

# ---------------------------------------------------------------------------
# 0. Sanity checks
# ---------------------------------------------------------------------------
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Log "Git is not installed (or not in PATH). Install 'Git for Windows' and retry." 'ERROR'
    Write-Log "Download: https://git-scm.com/download/win" 'ERROR'
    exit 1
}

# ---------------------------------------------------------------------------
# 1. Clone the repo once into a hidden helper folder (first run only)
# ---------------------------------------------------------------------------
if (-not (Test-Path -LiteralPath (Join-Path $RepoDir '.git'))) {
    Write-Log "First run: cloning $RepoUrl ..."
    $parent = Split-Path -Parent $RepoDir
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    & git clone --branch $Branch $RepoUrl $RepoDir 2>&1 | ForEach-Object { Write-Log $_ }
    if (-not (Test-Path -LiteralPath (Join-Path $RepoDir '.git'))) {
        Write-Log "Clone failed. Check the URL / internet / GitHub login." 'ERROR'
        exit 1
    }
    Write-Log "Clone complete." 'OK'
}

# Make sure we are on the right branch
& git -C $RepoDir checkout $Branch 2>&1 | Out-Null

# Make sure commits have an identity (needed for folder -> repo pushes)
$name = (Invoke-Git @('config', 'user.name')).Output
if ([string]::IsNullOrWhiteSpace($name)) {
    & git -C $RepoDir config user.name $GitName 2>&1 | Out-Null
}
$email = (Invoke-Git @('config', 'user.email')).Output
if ([string]::IsNullOrWhiteSpace($email)) {
    & git -C $RepoDir config user.email $GitEmail 2>&1 | Out-Null
}

# Make sure the target folder exists
if (-not (Test-Path -LiteralPath $Target)) {
    New-Item -ItemType Directory -Force -Path $Target | Out-Null
    Write-Log "Created target folder: $Target" 'OK'
}

# ---------------------------------------------------------------------------
# 2. Startup: pull latest, then align the target with the repo
# ---------------------------------------------------------------------------
$fetch = Invoke-Git @('fetch', 'origin', $Branch)
if ($fetch.Code -eq 0) {
    & git -C $RepoDir merge --ff-only "origin/$Branch" 2>&1 | Out-Null
}

$state      = Load-State
$repoHashes = Get-TreeHashes $RepoDir

if ($state.Count -eq 0) {
    Write-Log "First run: aligning target with repo (existing PC files are kept)..."
    foreach ($rel in $repoHashes.Keys) {
        $dst = Join-Path $Target (ConvertTo-OsPath $rel)
        if (-not (Test-Path -LiteralPath $dst)) {
            Copy-RepoToTarget -RelativePath $rel -RepoHash $repoHashes[$rel]
        }
    }
    foreach ($rel in $repoHashes.Keys) { $state[$rel] = $repoHashes[$rel] }
    Save-State $state
    Write-Log "Initial alignment done. New PC files will now be pushed to the repo." 'OK'
}

# ---------------------------------------------------------------------------
# 3. The watch loop (two-way)
# ---------------------------------------------------------------------------
Write-Log "=========================================================="
Write-Log " MonkeyCode instant sync is RUNNING (TWO-WAY)"
Write-Log " Repo   : $RepoUrl"
Write-Log " Branch : $Branch"
Write-Log " Target : $Target"
Write-Log " Scan   : every $Interval second(s)"
if ($OneWay) {
    Write-Log " Mode   : repo -> PC only (PC -> repo disabled)" 'WARN'
} else {
    Write-Log " Mode   : repo <-> PC"
}
Write-Log " Close this window to stop. Do not close otherwise."
Write-Log "=========================================================="

while ($true) {
    try {
        # ------------------------------------------------------------------
        # A. repo -> PC : fetch remote and copy anything that changed
        # ------------------------------------------------------------------
        $fetch = Invoke-Git @('fetch', 'origin', $Branch)
        if ($fetch.Code -ne 0) {
            Write-Log "Cannot reach GitHub right now. Retrying in $Interval s..." 'WARN'
        }
        else {
            $local  = (Invoke-Git @('rev-parse', 'HEAD')).Output
            $remote = (Invoke-Git @('rev-parse', "origin/$Branch")).Output

            # Only pull when our helper repo can fast-forward (no unpushed
            # local commits). This prevents overwriting PC edits.
            $canFastForward = $false
            if ($local -and $remote -and ($local -ne $remote)) {
                $ancestor = Invoke-Git @('merge-base', '--is-ancestor', $local, "origin/$Branch")
                $canFastForward = ($ancestor.Code -eq 0)
                if (-not $canFastForward) {
                    Write-Log "Local helper repo has unpushed commits; waiting for push first." 'WARN'
                }
            }

            if ($canFastForward) {
                $changedRaw = (Invoke-Git @('diff', '--name-only', $local, $remote)).Output
                $changed    = @($changedRaw -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ })
                $merge      = Invoke-Git @('merge', '--ff-only', "origin/$Branch")

                if ($merge.Code -ne 0) {
                    Write-Log "Could not fast-forward the helper repo. Will retry." 'WARN'
                }
                else {
                    Write-Log ("Remote change: {0} -> {1}" -f $local.Substring(0,7), $remote.Substring(0,7)) 'OK'

                    foreach ($rel in $changed) {
                        $relNorm   = $rel -replace '\\', '/'
                        $src       = Join-Path $RepoDir (ConvertTo-OsPath $relNorm)
                        $dst       = Join-Path $Target  (ConvertTo-OsPath $relNorm)
                        $repoHash  = if (Test-Path -LiteralPath $src) { Get-ContentHash $src } else { $null }
                        $targetHash = if (Test-Path -LiteralPath $dst) { Get-ContentHash $dst } else { $null }
                        $stateHash = $state[$relNorm]

                        # Both sides changed the same file since the last sync.
                        if ($stateHash -and $targetHash -and
                            ($targetHash -ne $stateHash) -and ($targetHash -ne $repoHash)) {
                            $backup = Backup-TargetFile -RelativePath $relNorm
                            Write-Log ("CONFLICT {0}: your PC copy was also changed." -f $relNorm) 'WARN'
                            if ($backup) { Write-Log ("         backup saved: {0}" -f $backup) 'WARN' }
                            Write-Log "         repo version wins for now (PC copy backed up above)." 'WARN'
                        }

                        Copy-RepoToTarget -RelativePath $relNorm -RepoHash $repoHash
                        if ($repoHash) { $state[$relNorm] = $repoHash } else { $state.Remove($relNorm) }
                    }

                    Save-State $state
                    Write-Log ("Repo -> PC: {0} file(s)." -f $changed.Count) 'OK'
                }
            }
        }

        # ------------------------------------------------------------------
        # B. PC -> repo : scan the target for local edits and push them
        # ------------------------------------------------------------------
        if (-not $OneWay) {
            $targetHashes = Get-TreeHashes $Target

            $toPush   = @{}
            $toDelete = @()

            foreach ($rel in $targetHashes.Keys) {
                if (-not $state.ContainsKey($rel)) {
                    $toPush[$rel] = $targetHashes[$rel]
                }
                elseif ($state[$rel] -ne $targetHashes[$rel]) {
                    $toPush[$rel] = $targetHashes[$rel]
                }
            }

            if ($AllowDelete) {
                foreach ($rel in $state.Keys) {
                    if (-not $targetHashes.ContainsKey($rel)) { $toDelete += $rel }
                }
            }

            if (($toPush.Count -gt 0) -or ($toDelete.Count -gt 0)) {
                # Copy the PC changes into the helper repo working tree.
                foreach ($rel in $toPush.Keys) {
                    $src    = Join-Path $Target  (ConvertTo-OsPath $rel)
                    $dst    = Join-Path $RepoDir (ConvertTo-OsPath $rel)
                    $dstDir = Split-Path -Parent $dst
                    if ($dstDir -and -not (Test-Path -LiteralPath $dstDir)) {
                        New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
                    }
                    Copy-Item -LiteralPath $src -Destination $dst -Force
                }
                foreach ($rel in $toDelete) {
                    $dst = Join-Path $RepoDir (ConvertTo-OsPath $rel)
                    if (Test-Path -LiteralPath $dst) { Remove-Item -LiteralPath $dst -Force }
                }

                Invoke-Git @('add', '-A') | Out-Null
                $status = (Invoke-Git @('status', '--porcelain')).Output

                if ($status) {
                    $commit = Invoke-Git @('commit', '-m', $CommitMessage)
                    if ($commit.Code -eq 0) {
                        Write-Log "PC -> REPO: committed changes." 'OK'
                    }
                    else {
                        Write-Log ("PC -> REPO: commit failed: {0}" -f $commit.Output) 'ERROR'
                    }
                }

                $aheadRaw = (Invoke-Git @('rev-list', '--count', "origin/$Branch..HEAD")).Output
                $ahead    = 0
                if ($aheadRaw -and [int]::TryParse($aheadRaw, [ref]$ahead)) { } else { $ahead = 0 }

                if ($ahead -gt 0) {
                    $push = Invoke-Git @('push', 'origin', $Branch)
                    if ($push.Code -eq 0) {
                        Write-Log ("PC -> REPO: pushed {0} change(s)." -f ($toPush.Count + $toDelete.Count)) 'PC'
                        foreach ($rel in $toPush.Keys) {
                            $rp = Join-Path $RepoDir (ConvertTo-OsPath $rel)
                            if (Test-Path -LiteralPath $rp) { $state[$rel] = Get-ContentHash $rp }
                        }
                        foreach ($rel in $toDelete) { $state.Remove($rel) }
                        Save-State $state
                    }
                    else {
                        Write-Log ("PC -> REPO: push failed (GitHub login/permissions?): {0}" -f $push.Output) 'ERROR'
                        Write-Log "The change is committed locally and will be pushed on the next try." 'WARN'
                    }
                }
                else {
                    # Nothing new to push (change already present in the repo).
                    foreach ($rel in $toPush.Keys) {
                        if ($targetHashes[$rel]) { $state[$rel] = $targetHashes[$rel] }
                    }
                    foreach ($rel in $toDelete) { $state.Remove($rel) }
                    Save-State $state
                }
            }
        }
    }
    catch {
        Write-Log ("Unexpected error: {0}" -f $_.Exception.Message) 'ERROR'
    }

    if ($Once) { break }
    Start-Sleep -Seconds $Interval
}
